export const ACTIONS_CONSTANTS = {
    FETCH_ALL: 'FETCH_ALL',
    FETCH_BY_SEARCH: 'FETCH_BY_SEARCH',
    FETCH_POST: 'FETCH_POST',
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    LIKE: 'LIKE',
    COMMENT_POST: 'COMMENT_POST',

    AUTH: 'AUTH',
    LOGOUT: 'LOGOUT',

    START_LOADING: 'START_LOADING',
    END_LOADING: 'END_LOADING',
}
